<script setup lang="ts">

</script>

<template>
  <q-card class="fit glass-container">
    <slot/>
  </q-card>
</template>

<style scoped lang="sass">
// TODO: 兼容旧版本firefox
.glass-container
  backdrop-filter: blur(25px) saturate(200%)
  -webkit-backdrop-filter: blur(25px) saturate(200%)
  background-color: rgba(255, 255, 255, 0)
  border-radius: 12px
/* Generated by https://generator.ui.glass/ */
</style>
